INSERT INTO CUSTOMER  (ID, NAME, SURNAME) VALUES (1,'Nihat', 'Kzly');
INSERT INTO CUSTOMER  (ID, NAME, SURNAME) VALUES (2,'Duman', 'Kzly');
INSERT INTO CUSTOMER (ID, NAME, SURNAME)VALUES (3,'Sebnem', 'Ozcan');